<?php
DEFINE('MYSQL_HOST', 'localhost');
DEFINE('MYSQL_USER', 'root');
DEFINE('MYSQL_PASSWORD', '');
DEFINE('MYSQL_PORT', NULL);
DEFINE('MYSQL_SOCKET', NULL);
DEFINE('MYSQL_DATABASE', 'merchandize_dev');